import { MockUser } from './types';

export const MOCK_USERS: MockUser[] = [
  {
    id: '1',
    name: 'TRACEY',
    pronouns: 'she/her',
    intention: 'matchmaking',
    matchPreferences: ['romantic-partner', 'relationship'],
    era: 2,
    traits: ['prefers 1:1', 'long walks', 'birding', 'slow replies ok', 'friends first'],
  },
  {
    id: '2',
    name: 'SEYI',
    pronouns: 'she/they',
    intention: 'matchmaking',
    matchPreferences: ['open-to-exploring', 'relationship', 'new-bestie'],
    era: 1,
    traits: ['deep convos pls', 'calling > texting', 'beach life', 'loves to host'],
  },
  {
    id: '3',
    name: 'DANI',
    pronouns: 'any pronouns',
    intention: 'matchmaking',
    matchPreferences: ['a-good-time', 'new-bestie', 'someone-to-go-out-with'],
    era: 0,
    traits: ['goofy', 'new friendships', 'enm', 'here for a good time', 'gathers the crew'],
  },
  {
    id: '4',
    name: 'HAYDEN',
    pronouns: 'they/them',
    intention: 'matchmaking',
    matchPreferences: ['open-to-exploring', 'new-bestie'],
    era: 1,
    traits: ['foodie', 'open', 'friends first', 'museum dates'],
  },
  {
    id: '5',
    name: 'ALEX',
    pronouns: 'he/they',
    intention: 'matchmaking',
    matchPreferences: ['romantic-partner', 'open-to-exploring'],
    era: 2,
    traits: ['bookworm', 'coffee addict', 'vinyl collector', 'slow mornings'],
  },
  {
    id: '6',
    name: 'JORDAN',
    pronouns: 'they/them',
    intention: 'matchmaking',
    matchPreferences: ['someone-to-go-out-with', 'a-good-time', 'new-bestie'],
    era: 0,
    traits: ['night owl', 'festival goer', 'spontaneous', 'dance floors'],
  },
  {
    id: '7',
    name: 'RILEY',
    pronouns: 'she/her',
    intention: 'matchmaking',
    matchPreferences: ['relationship', 'romantic-partner'],
    era: 2,
    traits: ['homebody', 'plant parent', 'cozy vibes', 'sunday brunches'],
  },
  {
    id: '8',
    name: 'SAM',
    pronouns: 'he/him',
    intention: 'matchmaking',
    matchPreferences: ['new-bestie', 'someone-to-go-out-with'],
    era: 1,
    traits: ['gym bro', 'hiking enthusiast', 'dog dad', 'brunch crew'],
  },
];
